name: CI
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: "ghcr.io/fwilhe2/dev:master"
    steps:
    - uses: actions/checkout@v2
    - name: Build Python
      run: |
        wget https://www.python.org/ftp/python/3.9.1/Python-3.9.1.tgz
        tar xzvf Python-3.9.1.tgz
        cd Python-3.9.1
        ./configure --prefix=$HOME/mypy/python
        make
        make install
        cd

    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: /home/runner/mypy/
